# Generated by Django 3.0.6 on 2020-05-11 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home_details',
            name='DAILY_THOUGHT',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='home_details',
            name='TODAY_WORD',
            field=models.TextField(max_length=200),
        ),
    ]
