# Generated by Django 3.0.6 on 2020-05-11 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200511_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='home_details',
            name='main_image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
