# Generated by Django 3.0.6 on 2020-05-14 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_home_details_main_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='book_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=200)),
                ('book_price', models.CharField(max_length=4)),
                ('book_dis_price', models.CharField(blank=True, max_length=4, null=True)),
                ('book_image', models.FileField(blank=True, null=True, upload_to='')),
                ('book_perview_page_one', models.TextField(max_length=100000)),
                ('book_preview_page_two', models.TextField(max_length=100000)),
            ],
        ),
        migrations.AlterField(
            model_name='home_details',
            name='DAILY_THOUGHT',
            field=models.TextField(max_length=100000),
        ),
    ]
