# Generated by Django 3.0.6 on 2020-05-17 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_contact_us_prayer_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques', models.CharField(max_length=500)),
                ('pot1', models.CharField(max_length=100)),
                ('pot2', models.CharField(max_length=100)),
                ('pot3', models.CharField(max_length=100)),
                ('pot4', models.CharField(max_length=100)),
                ('crt_ans', models.CharField(max_length=100)),
                ('token', models.BooleanField(default=False)),
            ],
        ),
    ]
