# Generated by Django 3.0.6 on 2020-05-18 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prayer_request',
            name='mail',
        ),
        migrations.AddField(
            model_name='prayer_request',
            name='option',
            field=models.CharField(default='hi', max_length=500),
        ),
    ]
