# Generated by Django 3.0.5 on 2020-05-27 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200518_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='prayer_request',
            name='email',
            field=models.EmailField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='prayer_request',
            name='option',
            field=models.CharField(max_length=500),
        ),
    ]
