# Generated by Django 3.0.6 on 2020-05-12 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0002_auto_20200510_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='permanent_reg',
            name='book_name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='temp_reg',
            name='book_name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
