# Generated by Django 3.0.6 on 2020-05-16 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0003_auto_20200512_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='notify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=10)),
            ],
        ),
    ]
